config/routes.rb
Rails.application.routes.draw do

  root 'sessions#index'

  get '/auth/:provider/callback' => 'sessions#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/events/popular_event' => 'events#popular_event'
  
  resources :events do 
    resources :attends, only: [:index, :new, :create]
  end
  

  resources :attends
  resources :users 
  resources :events


  #get 'events/bydate' => 'events/date'

  #get 'events/by_date', to: "events#by_date"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attend.rb
class Attend < ApplicationRecord
  belongs_to :user
  belongs_to :event

  #accepts_nested_attributes_for :user

  validates :guest, presence: true
  #scope :by_event, => (event_id) {where("event_id = ?", event_id)}

  validate :not_a_duplicate

  def not_a_duplicate
    if Attend.find_by(user_id: user_id, event_id: event_id)
      errors.add("attend", "you have already RSVPd")
    end
  end


end

app/models/event.rb
class Event < ApplicationRecord
    has_many :attends
    has_many :users, through: :attends
    validates :name, :date, :location, :details, presence: true
    #validates :date, numericality: {message: "%(value) must be included"}

    #accepts_nested_attributes_for :attends

    scope :order_by_date, -> {order(date: :asc)}

    scope :popular_event, -> {joins(:attends).group(:id).order('count(attends.id) desc').limit(1)}
  
    

end

app/models/user.rb
class User < ApplicationRecord
    has_many :attends
    has_many :events, through: :attends
    has_secure_password
    validates :name, presence: true
    validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    before_action :redirect_if_not_logged_in

    private

    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def redirect_if_not_logged_in
        redirect_to login_path if !logged_in?
    end

end

app/controllers/attends_controller.rb
class AttendsController < ApplicationController

    def index
        if params[:event_id] && event = Event.find_by_id(params[:event_id])
            #@attends = current_user.attends.by_event(params[:event_id])
            @attends = event.attends
        else
            @attends = current_user.attends
            #could be @attends = Attends.all
        end
    end
    
    def new
        @event = Event.find_by(id: params[:event_id])
        @user = User.find(session[:user_id])
        #binding.pry
        if params[:event_id] && event = Event.find_by_id(params[:event_id])
            @attend = event.attends.build 
        else
        @attend = Attend.new
        #@attend.build_user
        end 
    end

    def create
        @event = Event.find(attends_params[:event_id])
        @user = User.find(session[:user_id])
        @attend = Attend.create(attends_params)
        
        if @attend.save
            redirect_to events_path
           
         else
            flash[:message] = "Guest cannot be blank or you have already RSVPd!"
            redirect_to new_event_attend_path(@event)

        # redirect_to user_path(@user)
          end
    end

    private

    def attends_params
      params.require(:attend).permit(
         :user_id,
         :event_id,
         :guest,
         #user_attributes:[:name, :age, :email, :password]
      )
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

    before_action :set_event, only: [:show]

    def index
       # if params[:user_id]
        #    @events = User.find(params[:user_id]).events
         # else
        @events = Event.order_by_date
        
    #end
    end

    def new
        @event = Event.new
    end
    
    def create
        @event = Event.new(event_params)
        if @event.save
         redirect_to events_path
        else
         render :new
        end 
    end

    def popular_event
        @events = Event.popular_event
    end

    def show
       # @event = Event.find_by(id: params[:id])
        @attend = Attend.new
        @attend.build_user
        @user = User.find(session[:user_id])

        #@attends = Attend.all

    end

    def popular_events

    end

    private

    def event_params
        params.require(:event).permit(:name, :date, :location, :details)
    end

    def set_event
        @event = Event.find_by(id: params[:id])
        redirect_to events_path if !@event  
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :redirect_if_not_logged_in

    def index
    end

    def new
    end

    def create

        if params[:provider] == 'facebook'
 
            @user = User.find_or_create_by(uid: auth['uid']) do |u|
            u.name = auth['info']['name']
            u.email = auth['info']['email']
            u.password = SecureRandom.hex
         
          end
            @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
          @user = User.find_by(email: params[:user][:email])
            if @user && @user.authenticate(params[:user][:password])
                session[:user_id] = @user.id 
                redirect_to user_path(@user)
            else
                flash[:message] = "Incorrect email or password"
                redirect_to login_path
            end

        end
    end

    def destroy
        session.clear
        redirect_to root_path
    end

    private
 
    def auth
      request.env['omniauth.auth']
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    skip_before_action :redirect_if_not_logged_in, only: [:new, :create]

    def new
       @user = User.new
    end

    def create
       @user = User.new(user_params)
       if @user.save
        session[:user_id] = @user.id
        redirect_to user_path(@user)
       else
        render :new
       end 
    end

    def show
        @user = User.find_by(id: params[:id])
    end


    private

    def user_params
        params.require(:user).permit(:name, :age, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/attends_helper.rb
module AttendsHelper

    def display_header
        if params[:event_id]
            content_tag(:h1, "RSVPs:")
        else
            content_tag(:h1, "My RSVPs")
        end
    end

end

app/helpers/events_helper.rb
module EventsHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attends/index.html.erb
<%= display_header %>

<br>
<% @attends.each.with_index(1) do |f, index| %>
   
    <%= "#{index}. Number of guests: + #{f.guest}" %>
    <%= "added to #{f.event.name}" %>
  <br>
    <% end %>

 

app/views/attends/new.html.erb
<br><br>
<h1>Add Your RSVP</h1>

<%= render partial: "layouts/errors", locals: {object: @attend} %>

<h2><%= @attend.event.name %></h2>

<% if flash[:message] %>
<div class="message"><%= flash[:message] %></div>
<% end %><br>

<%= form_for(@attend) do |f|%>
    <%= f.hidden_field :user_id, :value => @user.id %>
    <%= f.hidden_field :event_id, :value => @event.id %>

    <%= f.label :guest, "How many guests will you bring?" %>
    <%= f.number_field :guest, min:0, max:3 %>
    <br>
    <br>
    

    <br>
    <br>
    <%= f.submit 'Attend this Event' %>
    <% end %>

app/views/events/index.html.erb
<br>
<br>
<h1>Upcoming Events</h1>
<% @events.each do |f| %>
   
    <li><%= link_to "#{f.name}", event_path(f) %></li>
    <li><%= f.date %></li>
    <li><%= f.location %></li>
    <li><%= link_to "RSVPs", event_attends_path(f) %></li>
    <li><%= link_to "Add an RSVP", new_event_attend_path(f) %></li>

    <br>
    <% end %>

app/views/events/new.html.erb
<h1>Create a New Event</h1>

<%= render partial: "layouts/errors", locals: {object: @event} %>

<%= form_for @event do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :date %>
    <%= f.text_field :date %>

    <%= f.label :location %>
    <%= f.text_field :location %>

    <%= f.label :details %>
    <%= f.text_area :details %>

    <%= f.submit 'Create Event' %>

    <% end %>

app/views/events/oldshow.html.erb
<h1><%= @event.name %></h1>
<h4>Date: <%= @event.date %></h4>
<h4>Location: <%= @event.location %></h4>
<h4>Details: <%= @event.details %></h4>

  

<%= form_for(@attend) do |f|%>
    <%= f.hidden_field :user_id, :value => @user.id %>
    <%= f.hidden_field :event_id, :value => @event.id %>

    <%= f.label :guest, "How many guests will you bring?" %>
    <%= f.number_field :guest %>
    <br>
    <br>
    <%= f.label :user_id, "Invite a user" %>
    <%= f.collection_select :user_id, User.all, :id, :name %>
    
    <h4>Or Create a User to Invite</h4>

    <%= f.fields_for :user do |u| %>
        
        <%= u.label :name %>
        <%= u.text_field :name %>
    
        <%= u.label :age %>
        <%= u.text_field :age %>
    
        <%= u.label :email %>
        <%= u.email_field :email, required:true %>
    
        <%= u.label :password %>
        <%= u.password_field :password %>
        <% end %>

    <br>
    <br>
    <%= f.submit 'Attend this Event' %>
    <% end %>

app/views/events/popular_event.html.erb
<br>
<br>
<h1>Check out the most popular event trending now!</h1>
<% @events.each do |f| %>
   
    <li><%= link_to "#{f.name}", event_path(f) %></li>
    <li><%= f.date %></li>
    <li><%= f.location %></li>
    <li><%= link_to "#{f.attends.count} RSVPs!!", event_attends_path(f) %></li> 
    <li><%= link_to "Add an RSVP", new_event_attend_path(f) %></li>

    <br>
    <% end %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<h4>Date: <%= @event.date %></h4>
<h4>Location: <%= @event.location %></h4>
<h4>Details: <%= @event.details %></h4>
<h4>Guests Attending: <% @event.users.uniq.each do |d| %></h4>
    <ul><%= d.name %></ul>
    <% end %>
<br>

<%= render partial: "layouts/errors", locals: {object: @attend} %>

<%= form_for(@attend) do |f|%>
    <%= f.hidden_field :user_id, :value => @user.id %>
    <%= f.hidden_field :event_id, :value => @event.id %>

    <%= f.label :guest, "How many guests will you bring?" %>
    <%= f.number_field :guest, min:0, max:3 %>
    <br>
    <br>
    

    <br>
    <br>
    <%= f.submit 'Attend this Event' %>
    <% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>
 
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsProj</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if logged_in? %>
  <%= link_to 'Logout', '/logout', method: :delete%> 
  <%= link_to 'Home', user_path(current_user) %>
  <%= link_to 'Events', events_path %>
  <%= link_to 'Create Event', new_event_path %> 
  <%= link_to 'RSVPs', attends_path %>
  <%= link_to 'Popular', events_popular_event_path %>
<% end %>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up Here</h1>


<%= render partial: "layouts/errors", locals: {object: @user} %>

<%= form_for @user do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :age %>
    <%= f.text_field :age %>

    <%= f.label :email %>
    <%= f.email_field :email, required:true %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.submit 'Sign Up' %>

    <% end %>

app/views/users/show.html.erb
<h1>Welcome <%=@user.name%></h1>



<p><%= @user.name %>'s Upcoming Events</p>


<% y = @user.events.uniq %>
<% y.each do |z| %>
<li><%= link_to "#{z.name}", event_path(z) %></li>
<br>
    <% end %>




    